{% set name = "nevergrad" %}
{% set version = "0.4.3.post9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d8800c7974a6a4ff494b075c95de81e68a309657b8e5ee3bc03b99600fe621d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - bayesian-optimization >=1.1.0
    - cma >=2.6.0
    - numpy >=1.15.0
    - pandas >=0.23.4
    - typing_extensions >=3.6.6
    - gym
    - pytorch
    - requests
    - matplotlib-base
    - Pillow
    - pyproj
    - torchvision
    - mixsimulator
    - iohexperimenter
    - opencv
    - image-quality
    - lpips
    - prophet
    - fcmaes
    - koncept
    - cdt

test:
  imports:
    - nevergrad
    - nevergrad.benchmark
    - nevergrad.common
    - nevergrad.functions
    - nevergrad.functions.arcoating
    - nevergrad.functions.games
    - nevergrad.functions.mlda
    - nevergrad.functions.multiobjective
    - nevergrad.functions.photonics
    - nevergrad.functions.powersystems
    - nevergrad.functions.rl
    - nevergrad.functions.stsp
    - nevergrad.optimization
    - nevergrad.parametrization

about:
  home: https://github.com/facebookresearch/nevergrad
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python toolbox for performing gradient-free optimization
  doc_url: https://facebookresearch.github.io/nevergrad/
  dev_url: https://github.com/facebookresearch/nevergrad

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
    - mxr-conda
    
